// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: ratwater.proto

package ratwater

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Ratwater_GRPC_Hello_FullMethodName = "/Ratwater_GRPC/Hello"
)

// Ratwater_GRPCClient is the client API for Ratwater_GRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Ratwater_GRPCClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type ratwater_GRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRatwater_GRPCClient(cc grpc.ClientConnInterface) Ratwater_GRPCClient {
	return &ratwater_GRPCClient{cc}
}

func (c *ratwater_GRPCClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Ratwater_GRPC_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ratwater_GRPCServer is the server API for Ratwater_GRPC service.
// All implementations must embed UnimplementedRatwater_GRPCServer
// for forward compatibility
type Ratwater_GRPCServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedRatwater_GRPCServer()
}

// UnimplementedRatwater_GRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRatwater_GRPCServer struct {
}

func (UnimplementedRatwater_GRPCServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedRatwater_GRPCServer) mustEmbedUnimplementedRatwater_GRPCServer() {}

// UnsafeRatwater_GRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Ratwater_GRPCServer will
// result in compilation errors.
type UnsafeRatwater_GRPCServer interface {
	mustEmbedUnimplementedRatwater_GRPCServer()
}

func RegisterRatwater_GRPCServer(s grpc.ServiceRegistrar, srv Ratwater_GRPCServer) {
	s.RegisterService(&Ratwater_GRPC_ServiceDesc, srv)
}

func _Ratwater_GRPC_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Ratwater_GRPCServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ratwater_GRPC_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Ratwater_GRPCServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ratwater_GRPC_ServiceDesc is the grpc.ServiceDesc for Ratwater_GRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ratwater_GRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ratwater_GRPC",
	HandlerType: (*Ratwater_GRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Ratwater_GRPC_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ratwater.proto",
}
